Repository MaSzyna-Reloaded/MaSzyna-API-wrapper, pull requests merged in 2024-12, with the labels that each got.

#31 Dev/GitHub actions cache
  .github/workflows/build.yaml
Labels: enhancement, github actions

#37 Add CodeQL
  .github/workflows/codeql.yml
Labels: github actions, C++

#44 Initial GitHub page docs
  .gitignore
  .tmux-dev
  Makefile
  docs/.bundle/config
  docs/.gitignore
  docs/404.html
  docs/Gemfile
  docs/Gemfile.lock
  docs/Makefile
  docs/_config.yml
  docs/architecture.md
  docs/assets/godot-logo.png
  docs/assets/maszyna-logo.jpg
  docs/assets/mover-architecture-overall.png
  docs/assets/overall-architecture-1.png
  docs/assets/overall-architecture-2.png
  docs/index.md
  docs/wrapping-mover.md
Labels: documentation

#36 Update README.md
  CODE_STYLE.md
  README.md
Labels: documentation, enhancement

#48 Add LogSystem
  addons/libmaszyna/developer_console.gd
  src/core/LogSystem.cpp
  src/core/LogSystem.hpp
  src/core/TrainController.cpp
  src/core/TrainPart.cpp
  src/core/TrainPart.hpp
  src/core/TrainSystem.cpp
  src/core/TrainSystem.hpp
  src/register_types.cpp
Labels: enhancement

#38 Setup .gitattributes
  .editorconfig
  .gitattributes
  README.md
Labels: enhancement

#67 Code cleanup
  .clang-format
  .clang-tidy
  .github/workflows/codeql.yml
  .github/workflows/qodana.yaml
  .gitignore
  Makefile
  README.md
  ci/qodana/generate_cmakelists.sh
  qodana.yaml
  src/brakes/TrainBrake.cpp
  src/brakes/TrainBrake.hpp
  src/core/GenericTrainPart.cpp
  src/core/GenericTrainPart.hpp
  src/core/LogSystem.cpp
  src/core/LogSystem.hpp
  src/core/TrainController.cpp
  src/core/TrainController.hpp
  src/core/TrainLogLevel.hpp
  src/core/TrainPart.cpp
  src/core/TrainPart.hpp
  src/core/TrainSystem.cpp
  src/core/TrainSystem.hpp
  src/core/utils.cpp
  src/core/utils.hpp
  src/doors/TrainDoors.cpp
  src/doors/TrainDoors.hpp
  src/editor/DieselEngineMasterControllerPowerItemEditor.cpp
  src/editor/DieselEngineMasterControllerPowerItemEditor.hpp
  src/engines/TrainDieselElectricEngine.cpp
  src/engines/TrainDieselElectricEngine.hpp
  src/engines/TrainDieselEngine.cpp
  src/engines/TrainDieselEngine.hpp
  src/engines/TrainElectricEngine.cpp
  src/engines/TrainElectricEngine.hpp
  src/engines/TrainElectricSeriesEngine.cpp
  src/engines/TrainElectricSeriesEngine.hpp
  src/engines/TrainEngine.cpp
  src/engines/TrainEngine.hpp
  src/plugin/LibMaszynaPlugin.hpp
  src/register_types.cpp
  src/systems/TrainSecuritySystem.cpp
  src/systems/TrainSecuritySystem.hpp
Labels: github actions, C++

#106 Add more useful documents and issue tempaltes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: enhancement
