Repository MaSzyna-Reloaded/MaSzyna-API-wrapper, pull requests merged in 2025-01, with the labels that each got.

#110 Smaller cleanup
  .clang-tidy
  CODE_STYLE.md
  src/brakes/TrainBrake.cpp
  src/brakes/TrainBrake.hpp
  src/core/TrainController.cpp
  src/core/TrainController.hpp
  src/core/TrainSystem.cpp
  src/core/TrainSystem.hpp
  src/core/utils.cpp
  src/core/utils.hpp
  src/doors/TrainDoors.cpp
  src/doors/TrainDoors.hpp
  src/engines/TrainDieselEngine.cpp
  src/engines/TrainDieselEngine.hpp
  src/engines/TrainElectricSeriesEngine.hpp
  src/parsers/maszyna_parser.cpp
  src/parsers/maszyna_parser.hpp
  src/register_types.cpp
  src/systems/TrainSecuritySystem.hpp
Labels: C++

#114 Fix broken feature_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: bug

#115 Remove Qodana comments
  .github/workflows/qodana.yaml
Labels: github actions, Qodana, CI/CD

#69 Update documentation for android development
  .gitignore
  README.md
  demo/export_presets.cfg
  demo/project.godot
Labels: documentation, android
